name: release-workflow
on: workflow_dispatch
jobs:
  build-apk-aab:
    runs-on: ubuntu-20.04
    name: Build release artifacts
    env:
      KEYSTORE_PASS: ${{ secrets.SIGN_KEY_STORE_PASS }}
      KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
      KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          { java-version: 11 }

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SIGN_KEY_REPO_NAME }}
          token: ${{ secrets.KEY_STORE_ACCESS_TOKEN }}
          path: keystore

      - name: Run build release
        run: |
          ./gradlew assembleRelease --stacktrace
          ./gradlew bundleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: app/build/outputs/release/app-release.apk

      - name: Upload AAB bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/release/app-release.aab